# latest dmd, gdc and ldc
language: d

matrix:
  include:
    - {os: linux, d: dmd}
    - {os: linux, d: ldc}
    - {os: linux, d: gdc}
    - {os: osx, d: dmd}
    - {os: osx, d: ldc}
    - {os: osx, d: gdc}
    - {os: linux, arc: arm64, d: dmd}
    - {os: linux, arc: ppc64le, d: dmd}
    - {os: linux, arc: s390x, d: dmd}
    
    #- {os: linux, d: dmd-2.071.0, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    #- {os: linux, d: ldc-1.0.0, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}

