# latest dmd, gdc and ldc

 
matrix:
  include:
    - stage: "DMD"
      language: d
      os: linux
      d: dmd
      name: "Linux"
    - language: d
      os: osx
      d: dmd
      name: "Mac"
    - language: d
      os: linux
      d: dmd
      env: ARCH="x86"
      addons: {apt: {packages: [[gcc-multilib]]}}
      script: dub test --arch "$ARCH"
      name: "X86"
    - stage: "LDC"
      language: d
      os: linux
      d: ldc
      name: "Linux"
    - language: d
      os: osx
      d: ldc
      name: "Mac"
    - language: d
      os: linux 
      arch: arm64
      d: ldc
      name: "Aarch64"
    - language: android
      dist: trusty
      d: ldc
      script:
        - dub test --compiler=${DC}
      name: "Android"
    - language: d
      os: linux
      d: ldc
      env: ARCH="x86"
      addons: {apt: {packages: [[gcc-multilib]]}}
      script: dub test --arch "$ARCH"
      name: "X86"

