# latest dmd, gdc and ldc
language: d

 
matrix:
  include:
    - os: linux,
      d: dmd
    - os: linux, 
      d: ldc
    - os: osx
      d: dmd
    - os: osx
      d: ldc
    - os: linux
      d: dmd
      env: ARCH="x86"
      script: dub test --arch "$ARCH"
    - os: linux
      d: ldc
      env: ARCH="x86"
      script: dub test --arch "$ARCH"
    - os: linux 
      arc: arm64
      d: ldc
    - os: linux 
      arc: s390x
      d: gdc
    - os: osx
      d: gdc
    - os: linux
      d: gdc
  allow_failures:
  - os: linux 
      arc: s390x
      d: gdc
    - os: osx
      d: gdc
    - os: linux
      d: gdc
