# latest dmd, gdc and ldc
language: d

matrix:
  include:
    - {os: linux, d: dmd}
    - {os: linux, d: ldc}
    - {os: linux, d: gdc}
    - {os: osx, d: dmd}
    - {os: osx, d: ldc}
    - {os: osx, d: gdc}

