# latest dmd, gdc and ldc
language: d

matrix:
  include:
    - {os: linux, d: dmd}
    - {os: linux, d: ldc}
    - {os: linux, d: gdc}
    - {os: osx, d: dmd}
    - {os: osx, d: ldc}
    - {os: osx, d: gdc}
 
 env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: dmd-2.071.0, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.0.0, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
script:
 - dub test --arch "$ARCH"
