# latest dmd, gdc and ldc
language: d

 
matrix:
  include:
  - stage: "dmd" 
      os: linux
      d: dmd
    - os: osx
      d: dmd
    - os: linux
      d: dmd
      env: ARCH="x86"
      addons: {apt: {packages: [[gcc-multilib]]}}
      script: dub test --arch "$ARCH"
  - stage: "ldc" 
      os: linux
      d: ldc
    - os: osx
      d: ldc
    - os: linux 
      arch: arm64
      d: ldc
      name: "Android"
    - os: linux
      d: ldc
      env: ARCH="x86"
      addons: {apt: {packages: [[gcc-multilib]]}}
      script: dub test --arch "$ARCH"
